
version: 2
exposures:
  
  - name: weekly_jaffle_metrics
    type: dashboard
    maturity: high
    description: >
      Did someone say "exponential growth"?
    
    depends_on:
      - source('dbtrmadav', 'testtable')
      
    owner:
      name: Claire from Data
      email: data@jaffleshop.com
sources:
  - name: dbtrmadav
    database: solar-cab-343813
    freshness: # default freshness
      warn_after: {count: 1, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: created_date

    tables:
      - name: testtable
        freshness: # make this a little more strict
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

